=== DKnight1900/AXUI/XML/schemas/AXUI_funcs.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:AXUI_funcs="AXUI_funcs" targetNamespace="AXUI_funcs" elementFormDefault="qualified">

    <xs:element name="funcs">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="AXUI_funcs:include" />
                <xs:element ref="AXUI_funcs:func" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="include">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="path" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="func">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="description" type="xs:string" />
            <xs:choice maxOccurs="unbounded">
                <xs:element name="step">
                    <xs:complexType>
                        <xs:attribute name="cmd" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== DKnight1900/AXUI/app_map/windows/windows_media_player_funcs.xml
<?xml version="1.0"?>
<AXUI_funcs:funcs xmlns:AXUI_funcs="AXUI_funcs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="AXUI_funcs AXUI_funcs.xsd">
    <AXUI_funcs:include_app_map name="wmplayer_app_map" path="windows_media_player.xml" />
    
    <AXUI_funcs:func name="func1" description="">
        <AXUI_funcs:step cmd="C:\Program Files\Windows Media Player\wmplayer"/>
    </AXUI_funcs:func>
    
    <AXUI_funcs:func name="func2" description="">
        <AXUI_funcs:step app_map="wmplayer_app_map" cmd="wmplayer.keyboard.input CTRL+M" />
    </AXUI_funcs:func>
    
    <AXUI_funcs:func name="func3" description="">
        <AXUI_funcs:step app_map="wmplayer_app_map" cmd="wmplayer.mouse.move" />
    </AXUI_funcs:func>
    
    <AXUI_funcs:func name="func4" description="">
        <AXUI_funcs:step app_map="wmplayer_app_map" cmd="wmplayer.WindowPattern.SetWindowVisualState "/>
    </AXUI_funcs:func>
    
</AXUI_funcs:funcs>
